### ISSUE TITLE
Stremio doesn't recognize the subdomain URL as a plugin.

### ISSUE THREAD

**Issue by ghost** [Stremio/stremio-static-addon-example#1]
It's a shame that the other issue was simply closed!
The subdomain is working...
![Screenshot 2023-07-03 084022](https://github.com/Stremio/stremio-static-addon-example/assets/91934182/01b85d97-1a73-482e-b0be-7328e15a88c6)
![Screenshot 2023-07-03 084250](https://github.com/Stremio/stremio-static-addon-example/assets/91934182/0ccf477f-01cb-4957-8990-ef254b7b97d4)

Subdomain: https://doku.17tv.info/manifest.json (dont work)
Long: https://17tv.info/stremio/dokukanal/manifest.json (work)

However, Stremio doesn't recognize the URL.

When I use the long URL, it works without any issues.

I kindly request assistance!

**Comment by TRtomasz** [comment]
both urls working fine for me

**Comment by ghost** [comment]
https://github.com/Stremio/stremio-static-addon-example/assets/91934182/67c56b72-c6cd-43aa-b3a5-2e6dcad256a4

Then I do not understand? There must be something wrong somewhere!?

**Comment by TRtomasz** [comment]
lol. why are you trying to open these links using "play url/magnet link" option?i have no idea why it even worked for the first link. This is to open video urls or magnet links not to open addons links

**Comment by ghost** [comment]
Because I assume that's how it's done?
I'm not a professional, but feel free to explain to me how I can offer my addon later!?

With this?
https://stremio.github.io/stremio-publish-addon/index.html

**Comment by TRtomasz** [comment]
This button says exactly "play url/magnet link" there is nothing suggesting it is used to open an addon.
If you have any issues with addon sdk you should open issues in addon sdk repository https://github.com/Stremio/stremio-addon-sdk
If you want to publish addon you can use `publishToCentral` https://github.com/Stremio/stremio-addon-sdk/blob/master/docs/README.md#publishtocentralurl
or use the web app you found https://stremio.github.io/stremio-publish-addon/index.html

**Comment by SannyQ** [comment]
Thx!

**Comment by ghost** [comment]
Thx!
